name = "Hugo Tania Theme"
license = "MIT"
licenselink = "https://github.com/danielkvist/hugo-tania-theme/blob/master/LICENSE"
description = "Tania is a very simple and clean theme for Hugo."
homepage = "https://github.com/danielkvist/hugo-tania-theme"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Danielkvist"
  homepage = "https://dkvist.com"
