baseURL = "/"
title = "Tania - Hugo Theme"
googleAnalytics = ""
enableRobotsTXT = true
language = "en-US"
copyright = ""

theme = "hugo-tania-theme"
themesDir = "../.."

[params]
  author = "Danielkvist"
  description = "Tania is a simple and clean theme for Hugo."

[params.contact]
  email = "danielkvist@protonmail.com"

[params.social]
  "500px" = ""
  codepen = "#"
  facebook = ""
  github = "#"
  gitlab = ""
  instagram = ""
  linkedin = "#"
  mastodon = ""
  pinterest = ""
  twitter = "#"
  weibo = ""
  youtube = ""