baseURL = "/"
title = "Tania - Hugo Theme"
googleAnalytics = ""
enableRobotsTXT = true
language = "en-US"
copyright = "© 2020 Daniel (Danielkvist). This theme is based entirely on the website of <a href=\"https://fossheim.io.\" alt=\"Sarah L. Fossheim\">Sarah L. Fossheim</a>."

theme = "hugo-tania-theme"
themesDir = "../.."

[params]
  author = "Danielkvist"
  description = "Tania is a simple and clean theme for Hugo."

[params.contact]
  text = ""
  email = "danielkvist@protonmail.com"

[params.social]
  text = ""

[params.links]
    "500px" = ""
    codepen = "#"
    facebook = ""
    github = "#"
    gitlab = ""
    instagram = ""
    linkedin = "#"
    mastodon = ""
    pinterest = ""
    twitter = "#"
    weibo = ""
    youtube = ""